using GetOnlyPropertyGenerator.Infos;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace GetOnlyPropertyGenerator;

using Info = (ContainingInfo containingInfo, EquatableArray<Result<FieldInfo>> fieldInfoResult);

[Generator(LanguageNames.CSharp)]
internal class Generator : IIncrementalGenerator
{
    const string HeaderAttributeName = "UnityEngine.HeaderAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var attributeName = "GenerateGetOnlyPropertyAttribute";
        var namespaceName = nameof(GetOnlyPropertyGenerator);

        context.RegisterPostInitializationOutput(initContext =>
        {
            var source = $$"""
            // <auto-generated/>
            namespace {{namespaceName}}
            {
                [global::System.AttributeUsage(global::System.AttributeTargets.Field, AllowMultiple = false)]
                internal sealed class {{attributeName}} : global::System.Attribute { }
            }
            """;

            initContext.AddSource($"{attributeName}.g.cs", source);
        });

        var fullName = $"{namespaceName}.{attributeName}";

        IncrementalValuesProvider<Info> provider = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                fullName,
                static (node, ct) => true,
                // 属性が付いた各フィールドごとに、(ContainingInfo, Result<FieldInfo>)を作成
                static (context, ct) =>
                {
                    var symbol = (IFieldSymbol)context.TargetSymbol;
                    var node = (VariableDeclaratorSyntax)context.TargetNode;

                    // フィールド名からプロパティ名を作成
                    // "_" プレフィックスがあれば、それを削除し、その次の文字を大文字にする
                    // なければ、先頭の文字を大文字にする
                    var startIdx = symbol.Name[0] == '_' && symbol.Name.Length >= 2 ? 1 : 0;
                    var propertyName =
                        char.ToUpperInvariant(symbol.Name[startIdx])
                        + symbol.Name.Substring(startIdx + 1);

                    DiagnosticInfo?[] array =
                    [
                        NoPartial(symbol, node),
                        AlreadyExist(symbol, node, propertyName),
                        PublicOrInternalField(symbol, node),
                        MustNotBeNested(symbol, node),
                    ];
                    EquatableArray<DiagnosticInfo> errors = new(array);

                    // Header属性があれば、それをsummaryに設定する
                    string summary = "";
                    foreach (AttributeData attribute in symbol.GetAttributes())
                    {
                        if (attribute.AttributeClass?.ToDisplayString() == HeaderAttributeName)
                        {
                            summary = (string)(attribute.ConstructorArguments[0].Value ?? "");
                            break;
                        }
                    }

                    // readonly を除く、修飾子も含めた型名を取得
                    // また、const は static に置換する
                    IEnumerable<string> typeNames = symbol
                        .ToDisplayString(Formatters.Formatter0)
                        .Split(' ')
                        .Where(static s => s is not "readonly")
                        .Select(static s => s is "const" ? "static" : s);
                    string typeName = string.Join(" ", typeNames.Take(typeNames.Count() - 1));

                    FieldInfo fi = new(
                        symbol.Name,
                        propertyName,
                        typeName,
                        summary,
                        LocationInfo.CreateFrom(node.Identifier.GetLocation())
                    );

                    ContainingInfo containingInfo = new(
                        symbol.ContainingType.ToDisplayString(Formatters.Formatter1),
                        symbol.ContainingType.ToDisplayString(Formatters.Formatter2),
                        symbol.ContainingNamespace.ToDisplayString(Formatters.Formatter2),
                        symbol.ContainingNamespace.IsGlobalNamespace
                    );

                    return (containingInfo, fieldInfoResult: new Result<FieldInfo>(fi, errors));
                }
            )
            .Collect()
            // 同じ型ごとにまとめる(Info型にする)
            .Select(
                static (array, ct) =>
                {
                    IEnumerable<
                        IGrouping<
                            string,
                            (ContainingInfo containingInfo, Result<FieldInfo> fieldInfoResult)
                        >
                    > group = array.GroupBy(item => item.containingInfo.ContainingTypeFullName);

                    var values = new EquatableArray<Info>([
                        .. group.Select(a =>
                            (
                                a.First().containingInfo,
                                new EquatableArray<Result<FieldInfo>>([
                                    .. a.AsEnumerable().Select(a => a.fieldInfoResult),
                                ])
                            )
                        ),
                    ]);
                    return values;
                }
            )
            .SelectMany(static (v, ct) => v);

        // コードを生成
        context.RegisterSourceOutput(provider, Emit);
    }

    private static DiagnosticInfo? NoPartial(IFieldSymbol symbol, VariableDeclaratorSyntax node)
    {
        var t = node.FirstAncestorOrSelf<TypeDeclarationSyntax>();
        if (t is not null && !t.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
        {
            return new DiagnosticInfo(
                GetOnlyPropertyGeneratorDiagnosticDescriptors.MustBePartial,
                t.Identifier.GetLocation(),
                symbol.ContainingType.Name
            );
        }
        return null;
    }

    private static DiagnosticInfo? AlreadyExist(
        IFieldSymbol symbol,
        VariableDeclaratorSyntax node,
        string generatedPropertyName
    )
    {
        bool hasSameProperty = symbol
            .ContainingType.GetMembers(generatedPropertyName)
            .Where(a => a is IFieldSymbol || a is IPropertySymbol)
            .Any();
        if (hasSameProperty)
        {
            return new DiagnosticInfo(
                GetOnlyPropertyGeneratorDiagnosticDescriptors.AlreadyExist,
                node.Identifier.GetLocation(),
                generatedPropertyName
            );
        }
        return null;
    }

    private static DiagnosticInfo? PublicOrInternalField(
        IFieldSymbol symbol,
        VariableDeclaratorSyntax node
    )
    {
        bool hasPublicOrInternal = symbol.DeclaredAccessibility switch
        {
            Accessibility.Private
            or Accessibility.ProtectedAndInternal
            or Accessibility.Protected => false,
            _ => true,
        };

        if (hasPublicOrInternal)
        {
            return new DiagnosticInfo(
                GetOnlyPropertyGeneratorDiagnosticDescriptors.PublicOrInternalField,
                node.Identifier.GetLocation(),
                symbol.Name
            );
        }
        return null;
    }

    private static DiagnosticInfo? MustNotBeNested(
        IFieldSymbol symbol,
        VariableDeclaratorSyntax node
    )
    {
        var t = node.FirstAncestorOrSelf<TypeDeclarationSyntax>();
        if (t?.Parent is TypeDeclarationSyntax)
        {
            return new DiagnosticInfo(
                GetOnlyPropertyGeneratorDiagnosticDescriptors.MustNotBeNested,
                t.Identifier.GetLocation(),
                symbol.ContainingType.Name
            );
        }
        return null;
    }

    private static void Emit(SourceProductionContext sourceProductionContext, Info info)
    {
        // エラーを表示
        if (ReportErrors(sourceProductionContext, info))
        {
            return;
        }

        // ソースコードの内容を作成
        string source = CreateSource(info);

        // ソースコードを追加
        AddSource(sourceProductionContext, info, source);
    }

    private static bool ReportErrors(SourceProductionContext sourceProductionContext, Info info)
    {
        bool isError = false;
        foreach (Result<FieldInfo>? result in info.fieldInfoResult)
        {
            if (result is null)
            {
                continue;
            }
            foreach (DiagnosticInfo? diag in result.Errors)
            {
                if (diag is null)
                {
                    continue;
                }
                isError = true;
                sourceProductionContext.ReportDiagnostic(
                    Diagnostic.Create(diag.Descriptor, diag.Location?.ToLocation(), diag.Message)
                );
            }
        }
        isError |= DuplicateGeneration(sourceProductionContext, info);
        return isError;
    }

    private static bool DuplicateGeneration(
        SourceProductionContext sourceProductionContext,
        Info info
    )
    {
        bool isError = false;
        HashSet<string> hashSet = [];
        foreach (Result<FieldInfo>? result in info.fieldInfoResult)
        {
            if (result is null)
            {
                continue;
            }
            if (!hashSet.Add(result.Value.GeneratedPropertyName))
            {
                isError = true;
                sourceProductionContext.ReportDiagnostic(
                    Diagnostic.Create(
                        GetOnlyPropertyGeneratorDiagnosticDescriptors.DuplicateGeneration,
                        result.Value.Location?.ToLocation(),
                        result.Value.GeneratedPropertyName
                    )
                );
            }
        }
        return isError;
    }

    private static string CreateSource(Info info)
    {
        var nsBegin = info.containingInfo.ContainingNamespaceIsGlobalNamespace
            ? ""
            : $"namespace {info.containingInfo.ContainingNamespaceFullName} {{";

        var nsEnd = info.containingInfo.ContainingNamespaceIsGlobalNamespace ? "" : "}";

        var sourceBegin = $$"""
            // <auto-generated/>

            #nullable enable
            #pragma warning disable CS8600
            #pragma warning disable CS8601
            #pragma warning disable CS8602
            #pragma warning disable CS8603
            #pragma warning disable CS8604

            {{nsBegin}}
                partial {{info.containingInfo.ContainingTypeNameIncludedTypeKeyword}}
                {

            """;

        var sourceEnd = $$"""
                }
            {{nsEnd}}
            """;

        foreach (Result<FieldInfo>? result in info.fieldInfoResult)
        {
            if (result is null)
            {
                continue;
            }
            sourceBegin += $$"""
                        /// <summary>
                        /// {{result.Value.PropertySummary}}
                        /// </summary>
                        public {{result.Value.TypeFullName}} {{result.Value.GeneratedPropertyName}} => {{result.Value.Name}};

                """;
        }
        return sourceBegin + sourceEnd;
    }

    private static void AddSource(
        SourceProductionContext sourceProductionContext,
        Info info,
        string source
    )
    {
        var fullType = info
            .containingInfo.ContainingTypeFullName.Replace('<', '_')
            .Replace('>', '_')
            .Replace(',', '_')
            .Replace(" ", "");

        sourceProductionContext.AddSource($"{fullType}.g.cs", source);
    }
}
